export const FIELD_LABELS: Record<string, string> = {
  kenteken: 'Kenteken',
  voertuigsoort: 'Voertuigsoort',
  merk: 'Merk',
  handelsbenaming: 'Model',
  type: 'Type',
  variant: 'Variant',
  uitvoering: 'Uitvoering',
  inrichting: 'Inrichting',
  eerste_kleur: 'Kleur',
  tweede_kleur: 'Tweede kleur',
  lengte: 'Lengte',
  breedte: 'Breedte',
  hoogte_voertuig: 'Hoogte',
  wielbasis: 'Wielbasis',
  cilinderinhoud: 'Cilinderinhoud',
  aantal_cilinders: 'Cilinders',
  nettomaximumvermogen: 'Vermogen',
  maximale_constructiesnelheid: 'Snelheid',
  massa_ledig_voertuig: 'Massa ledig',
  massa_rijklaar: 'Massa rijklaar',
  toegestane_maximum_massa_voertuig: 'Max massa',
  technische_max_massa_voertuig: 'Tech max massa',
  maximum_massa_trekken_ongeremd: 'Max trek ongeremd',
  maximum_trekken_massa_geremd: 'Max trek geremd',
  maximum_massa_samenstelling: 'Max massa totaal',
  brandstof_omschrijving: 'Brandstof',
  emissiecode_omschrijving: 'Emissieklasse',
  emissie_co2_gecombineerd_wltp: 'CO2 (WLTP)',
  co2_uitstoot_gecombineerd: 'CO2 gecombineerd',
  brandstof_verbruik_gecombineerd_wltp: 'Verbruik (WLTP)',
  geluidsniveau_stationair: 'Geluidsniveau stationair',
  toerental_geluidsniveau: 'Toerental geluid',
  milieuklasse_eg_goedkeuring_licht: 'Milieuklasse EG',
  uitlaatemissieniveau: 'Uitlaatemissie',
  vervaldatum_apk: 'APK vervaldatum',
  datum_eerste_toelating: 'Eerste toelating',
  datum_eerste_tenaamstelling_in_nederland: 'Eerste tenaamstelling NL',
  datum_tenaamstelling: 'Tenaamstelling',
  catalogusprijs: 'Catalogusprijs',
  bruto_bpm: 'Bruto BPM',
  europese_voertuigcategorie: 'EU-categorie',
  taxi_indicator: 'Taxi',
  export_indicator: 'Geëxporteerd',
  wam_verzekerd: 'WAM verzekerd',
  tenaamstellen_mogelijk: 'Tenaam mogelijk',
  typegoedkeuringsnummer: 'Typegoedkeuring',
  volgnummer_wijziging_eu_typegoedkeuring: 'EU typegoedkeuring volgnr',
  vermogen_massarijklaar: 'Vermogen/massa',
  openstaande_terugroepactie_indicator: 'Terugroepactie',
  tellerstandoordeel: 'Tellerstand oordeel',
  code_toelichting_tellerstandoordeel: 'Tellerstand code',
  jaar_laatste_registratie_tellerstand: 'Laatste tellerregistratie',
  wacht_op_keuren: 'Wacht op keuren',
  registratie_datum_goedkeuring_afschrijvingsmoment_bpm: 'BPM registratiedatum',
  as_nummer: 'Asnummer',
  aantal_assen: 'Aantal assen',
  aangedreven_as: 'Aangedreven as',
  plaatscode_as: 'Plaatscode as',
  spoorbreedte: 'Spoorbreedte',
  wettelijk_toegestane_maximum_aslast: 'Wettelijk max aslast',
  technisch_toegestane_maximum_aslast: 'Technisch max aslast',
  afstand_tot_volgende_as_voertuig: 'Afstand tot volgende as',
  import_status: 'Herkomst',
  brandstof_volgnummer: 'Brandstof volgnummer',
  aantal_deuren: 'Aantal deuren',
  aantal_zitplaatsen: 'Aantal zitplaatsen',
  aantal_wielen: 'Aantal wielen',
  geluidsniveau_rijdend: 'Geluidsniveau rijden',
  brandstofverbruik_buiten: 'Verbruik buiten',
  brandstofverbruik_stad: 'Verbruik stad',
  brandstofverbruik_gecombineerd: 'Verbruik gecombineerd',
};

export interface DataSection {
  title: string;
  icon: string;
  fields: string[];
  source?: 'vehicle' | 'fuel' | 'axles';
}

export const DATA_SECTIONS: DataSection[] = [
  {
    title: 'Voertuig',
    icon: 'directions_car',
    fields: ['merk', 'handelsbenaming', 'voertuigsoort', 'type', 'variant', 'uitvoering', 'inrichting', 'eerste_kleur', 'tweede_kleur'],
  },
  {
    title: 'Registratie',
    icon: 'calendar_today',
    fields: ['vervaldatum_apk', 'datum_eerste_toelating', 'datum_eerste_tenaamstelling_in_nederland', 'datum_tenaamstelling', 'import_status', 'typegoedkeuringsnummer', 'volgnummer_wijziging_eu_typegoedkeuring', 'wacht_op_keuren'],
  },
  {
    title: 'Motor',
    icon: 'settings',
    fields: ['nettomaximumvermogen', 'cilinderinhoud', 'aantal_cilinders', 'maximale_constructiesnelheid', 'vermogen_massarijklaar'],
  },
  {
    title: 'Brandstof & Milieu',
    icon: 'eco',
    source: 'fuel',
    fields: ['brandstof_omschrijving', 'brandstof_volgnummer', 'emissiecode_omschrijving', 'emissie_co2_gecombineerd_wltp', 'co2_uitstoot_gecombineerd', 'brandstof_verbruik_gecombineerd_wltp', 'brandstofverbruik_buiten', 'brandstofverbruik_stad', 'brandstofverbruik_gecombineerd', 'milieuklasse_eg_goedkeuring_licht', 'uitlaatemissieniveau', 'geluidsniveau_stationair', 'toerental_geluidsniveau', 'geluidsniveau_rijdend'],
  },
  {
    title: 'Afmetingen',
    icon: 'straighten',
    fields: ['lengte', 'breedte', 'hoogte_voertuig', 'wielbasis', 'aantal_deuren', 'aantal_zitplaatsen', 'aantal_wielen'],
  },
  {
    title: 'Gewicht',
    icon: 'scale',
    fields: ['massa_rijklaar', 'massa_ledig_voertuig', 'toegestane_maximum_massa_voertuig', 'technische_max_massa_voertuig', 'maximum_massa_trekken_ongeremd', 'maximum_trekken_massa_geremd', 'maximum_massa_samenstelling'],
  },
  {
    title: 'Kosten',
    icon: 'payments',
    fields: ['catalogusprijs', 'bruto_bpm', 'registratie_datum_goedkeuring_afschrijvingsmoment_bpm'],
  },
  {
    title: 'Status',
    icon: 'info',
    fields: ['europese_voertuigcategorie', 'taxi_indicator', 'export_indicator', 'wam_verzekerd', 'tenaamstellen_mogelijk', 'openstaande_terugroepactie_indicator', 'tellerstandoordeel', 'code_toelichting_tellerstandoordeel', 'jaar_laatste_registratie_tellerstand'],
  },
];

export const AXLE_FIELDS = [
  { key: 'as_nummer', label: 'Asnummer' },
  { key: 'aangedreven_as', label: 'Aangedreven' },
  { key: 'plaatscode_as', label: 'Plaatscode' },
  { key: 'spoorbreedte', label: 'Spoorbreedte' },
  { key: 'wettelijk_toegestane_maximum_aslast', label: 'Wettelijk max' },
  { key: 'technisch_toegestane_maximum_aslast', label: 'Technisch max' },
  { key: 'afstand_tot_volgende_as_voertuig', label: 'Afstand volgende' },
];
